# Generated by Django 5.1.1 on 2024-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
