# Generated by Django 5.1.1 on 2024-10-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0002_alter_categoryoffer_end_date_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
