# Generated by Django 5.1.1 on 2024-09-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_main_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
