# Generated by Django 5.0.7 on 2024-08-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_images_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
