# Generated by Django 5.0.7 on 2024-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=150, upload_to='product_images/'),
        ),
    ]
