# Generated by Django 5.0.7 on 2024-08-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
    ]
