# Generated by Django 5.1.1 on 2024-11-22 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0002_rename_timestamp_wallettransaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_wallet.wallet'),
            preserve_default=False,
        ),
    ]
