# Generated by Django 5.1.1 on 2024-10-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_order_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_amount',
        ),
    ]
