# Generated by Django 5.1.1 on 2024-11-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
