# Generated by Django 5.1.1 on 2024-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_id_gen',
        ),
    ]
