# Generated by Django 5.1.1 on 2024-11-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_rename_order_id_order_order_id_gen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id_gen',
            new_name='order_id',
        ),
    ]
