# Generated by Django 5.1.1 on 2024-09-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
        ('products', '0004_productvariant_is_main_variant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
