# Generated by Django 5.1.1 on 2024-10-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
        ('coupon_management', '0002_remove_coupon_discount_coupon_coupon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupon'),
        ),
    ]
