# Generated by Django 5.1.1 on 2024-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_wishlist'),
        ('products', '0002_productvariant_unique_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='products.product'),
        ),
    ]
